name: Build DLL

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
      - uses: actions/checkout@v4

      - name: Compile (${{ matrix.arch }})
        shell: cmd
        run: |
          if "${{ matrix.arch }}"=="x64" (
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ) else (
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          )

          cl /c /O2 /MT disasmlen.c
          cl /c /O2 /MT /Yc"pch.h" /Fp"pch.pch" pch.cpp
          cl /c /O2 /MT /Yu"pch.h" /Fp"pch.pch" dllmain.cpp keygen.cpp direct_hook.cpp

          link /DLL /OUT:aida64-hook-${{ matrix.arch }}.dll ^
            dllmain.obj keygen.obj direct_hook.obj disasmlen.obj pch.obj ^
            version.lib advapi32.lib

      - name: Upload artifact (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: aida64-hook-${{ matrix.arch }}
          path: aida64-hook-${{ matrix.arch }}.dll
